## NAMA: MUHAMMAD NAUFAL IHSAN MAULIDIN
## NIM: 2109106034
## KELAS: INFORMATIKA A2 2021
## POSTTEST 7 KB

### IMPORT LIBRARY TENSORFLOW YANG AKAN DIGUNAKAN

In [1]:
import tensorflow as tf

### MEMBUAT VARIABEL RANDOM_TENSOR [5,5]

In [2]:
random_tensor = tf.random.normal([5,5], seed=1)

In [3]:
random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

### MEMBUAT VARIABEL PRIME_TENSOR BILANGAN PRIMA [5,5]

In [4]:
list1 = [2,3,5,7,11], [13,17,19,23,29], [31, 37, 41, 43, 47], [53, 59, 61, 67, 71], [73, 79, 83, 89, 97]


prime_tensor = tf.convert_to_tensor(list1, dtype = tf.float32)

In [5]:
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

### TAMPILKAN DIMENSI KEDUA VARIABEL

In [9]:
print("Dimensi Variabel Random =",random_tensor.shape)

Dimensi Variabel Random = (5, 5)


In [11]:
print("Dimensi Variabel Prime =", prime_tensor.shape)

Dimensi Variabel Prime = (5, 5)


### OPERASI ARITMETIKA

#### 1.) PENJUMLAHAN

In [54]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 3.0767934  3.7302108  4.3937006  5.6766787 11.572046 ]
 [13.4062395 16.515495  18.449005  22.617462  27.632383 ]
 [29.683523  38.72908   41.359016  41.99056   46.51821  ]
 [51.044933  59.425167  61.905468  67.51601   71.820786 ]
 [73.51527   78.88974   84.12163   88.8173    96.01716  ]], shape=(5, 5), dtype=float32)


#### 2.) PENGURANGAN

In [59]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -0.92320657  -2.2697892   -5.6062994   -8.323321   -10.427954  ]
 [-12.5937605  -17.484505   -19.550995   -23.382538   -30.367617  ]
 [-32.316475   -35.27092    -40.640984   -44.00944    -47.48179   ]
 [-54.955067   -58.574833   -60.094532   -66.48399    -70.179214  ]
 [-72.48473    -79.11026    -81.87837    -89.1827     -97.98284   ]], shape=(5, 5), dtype=float32)


#### 3.) PERKALIAN

In [60]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[   2.1535869    2.1906319   -3.0314972   -9.2632475    6.2925086]
 [   5.2811136   -8.236585   -10.468915    -8.798384   -39.660877 ]
 [ -40.81077     63.975994    14.719699   -43.40595    -22.644089 ]
 [-103.61845     25.084763    55.233448    34.572483    58.27584  ]
 [  37.614635    -8.710547    93.09525    -16.260405   -95.33581  ]], shape=(5, 5), dtype=float32)


#### 4.) PEMBAGIAN

In [61]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[ 0.5383967   0.24340355 -0.12125989 -0.18904588  0.0520042 ]
 [ 0.03124919 -0.02850029 -0.02899976 -0.0166321  -0.04715919]
 [-0.04246698  0.04673192  0.00875651 -0.02347536 -0.01025083]
 [-0.03688802  0.00720619  0.01484371  0.0077016   0.01156037]
 [ 0.00705848 -0.0013957   0.01351361 -0.00205282 -0.01013241]], shape=(5, 5), dtype=float32)


#### 5.) PANGKAT

In [62]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.1594841e+00  3.8935387e-01 -8.1928670e-02 -7.1065149e+00
   2.1465565e-03]
 [ 8.2066908e-06 -4.4675558e-06 -1.2072950e-05 -2.5207283e-10
  -8.7692979e+03]
 [-5.0327441e+03  6.2974790e+08  5.7506609e-19 -1.4978701e+00
  -1.2424513e-15]
 [-2.7011194e+15  1.2159660e-22  2.3399794e-03  5.5967409e-20
   8.1347395e-07]
 [ 9.5166029e-22 -0.0000000e+00  1.3724774e+04 -0.0000000e+00
  -1.8662918e-01]], shape=(5, 5), dtype=float32)


#### 6.) LOGARITMA

In [63]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[ 0.07398757 -0.31442222         nan         nan -0.5585355 ]
 [-0.9008124          nan         nan         nan         nan]
 [        nan  0.54759    -1.0243855          nan         nan]
 [        nan -0.8552768  -0.09930514 -0.66163456 -0.19749229]
 [-0.6630662          nan  0.11478261         nan         nan]], shape=(5, 5), dtype=float32)


### NILAI MAX AND MIN DARI RANDOM_TENSOR

In [12]:
#Nilai Max Baris random_tensor
tf.argmax(random_tensor, axis = 0).numpy()

array([2, 0, 2, 2, 3], dtype=int64)

In [17]:
#Nilai Max Kolom random_tensor
tf.argmax(random_tensor, axis = 1).numpy()

array([1, 1, 2, 4, 4], dtype=int64)

In [18]:
#Nilai Min Baris random_tensor
tf.argmin(random_tensor, axis = 0).numpy()

array([4, 4, 1, 0, 2], dtype=int64)

In [19]:
#Nilai Min Kolom random_tensor
tf.argmin(random_tensor, axis = 1).numpy()

array([3, 2, 4, 0, 0], dtype=int64)

### PENGGABUNGAN (CONCAT) KEDUA VARIABEL

In [20]:
# CONCAT ISI VARIABEL BARIS
tf.concat([random_tensor, prime_tensor],axis = 0).numpy()

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01]], dtype=float32)

In [22]:
# CONCAT ISI VARIABEL KOLOM
tf.concat([random_tensor, prime_tensor],axis = 1).numpy()

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         6.7000000e+01,  7.1000000e+01],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00,  7.3000000e+01,  7.9000000e+01,  8.3000000e+01,
         8.9000000e+01,  9.7000000e+01]], dtype=float32)

In [23]:
# CONCAT DALAM BENTUK SHAPE BARIS
tf.concat([random_tensor, prime_tensor],axis= 0).shape

TensorShape([10, 5])

In [25]:
# CONCAT DALAM BENTUK SHAPE KOLOM
tf.concat([random_tensor, prime_tensor],axis= 1).shape

TensorShape([5, 10])

### SORTING DESCENDING KEDUA VARIABLE

##### a.) RANDOM_TENSOR

In [69]:
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[ 1.0767934 ,  0.73021066,  0.5720462 , -0.60629946, -1.3233211 ],
       [ 0.4062395 , -0.3825384 , -0.48450497, -0.5509955 , -1.3676164 ],
       [ 1.7290809 ,  0.35901704, -0.48178914, -1.0094407 , -1.3164763 ],
       [ 0.9054664 ,  0.8207865 ,  0.5160072 ,  0.42516547, -1.955065  ],
       [ 1.1216296 ,  0.515269  , -0.11026009, -0.18270119, -0.9828434 ]],
      dtype=float32)

In [26]:
tf.argsort(random_tensor, direction="DESCENDING").numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

#### b.) PRIME_TENSOR

In [70]:
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)

In [27]:
tf.argsort(prime_tensor, direction="DESCENDING").numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])

### SELESAI
### TERIMA KASIH